######################################################################
# Automatically generated by qmake (2.01a) lun. ao�t 2 12:43:33 2010
######################################################################

TEMPLATE = app
TARGET = enttec_open_usb_dmx
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
LIBS += -lftdi -lpthread


# Input
SOURCES += enttec_open_usb_dmx.c
